language: c

compiler:
    - clang
before_script:
    - pwd
    - cd ..
    - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/decompress-samples.sh
    - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/decompress-samples-extra.sh
    - wget --no-check-certificate https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
    - tar xf cmocka-1.1.0.tar.xz
    - cd cmocka-1.1.0
    - sudo apt-get -y install cmake
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
    - make
    - sudo make install
    - cd ../../udftools
script:
    - ./autogen.sh --enable-debug 
    - ./configure --enable-debug
    - make
    - cd ..
    - wget --no-check-certificate https://pac.chapadla.cz/~rain/udffsck-test-samples/udf-samples.tar.xz 
    - bash decompress-samples.sh
    - cd udftools/udffsck
    - ./test
    - cd ../..
    - rm udf-samples.tar.xz udf-samples -r
    - wget --no-check-certificate https://pac.chapadla.cz/~rain/udffsck-test-samples/udf-samples-extra.tar.xz 
    - bash decompress-samples-extra.sh
    - cd udftools/udffsck
    - ./testextra
    
