language: c

#env:
#  - TESTS=
#  - TESTS=--enable-tests TESTLEVEL=unit
#  - TESTS=--enable-tests TESTLEVEL=basic
#  - TESTS=--enable-tests TESTLEVEL=extra1
#  - TESTS=--enable-tests TESTLEVEL=extra2


matrix:
  include:
    - compiler: gcc-4.4
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.4-multilib
              #        - gccgo:i386
            - golang-go:i386
            - perl:i386
    - compiler: gcc-4.4
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - gcc-4.4
            - gccgo
            - golang-go
    - compiler: gcc-4.6
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.6-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc-4.6
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - gcc-4.6
            - gccgo
            - golang-go
    - compiler: gcc-4.7
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.7-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc-4.7
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - gcc-4.7
            - gccgo
            - golang-go
    - compiler: gcc-4.8
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.8-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc-4.8
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - gcc-4.8
            - gccgo
            - golang-go
    - compiler: gcc-4.9
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-4.9-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc-4.9
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-4.9
            - gccgo
            - golang-go
    - compiler: gcc-5
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-5-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc-5
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-5
            - gccgo
            - golang-go
    - compiler: gcc-6
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-6-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc-6
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-6
            - gccgo
            - golang-go
    - compiler: gcc-7
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-7-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc-7
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libreadline-dev
            - gcc-7
            - gccgo
            - golang-go
    - compiler: clang-3.3
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.3
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-3.3
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.3
            - gccgo
            - golang-go
    - compiler: clang-3.4
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.4
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-3.4
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.4
            - gccgo
            - golang-go
    - compiler: clang-3.5
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.5
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-3.5
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.5
            - gccgo
            - golang-go
    - compiler: clang-3.6
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.6
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.6
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-3.6
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.6
          packages:
            - libreadline-dev
            - clang-3.6
            - gccgo
            - golang-go
    - compiler: clang-3.7
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.7
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.7
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-3.7
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.7
          packages:
            - libreadline-dev
            - clang-3.7
            - gccgo
            - golang-go
    - compiler: clang-3.8
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.8
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-3.8
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.8
            - gccgo
            - golang-go
    - compiler: clang-3.9
      env: PLATFORM=x86
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-3.9
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-3.9
      env: PLATFORM=x86_64
      addons:
        apt:
          packages:
            - libreadline-dev
            - clang-3.9
            - gccgo
            - golang-go
    - compiler: clang-4.0
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-4.0
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-4.0
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - libreadline-dev
            - clang-4.0
            - gccgo
            - golang-go
    - compiler: clang-5.0
      env: PLATFORM=x86
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - clang-5.0
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang-5.0
      env: PLATFORM=x86_64
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - libreadline-dev
            - clang-5.0
            - gccgo
            - golang-go
    - compiler: gcc
      dist: precise
      env: PLATFORM=x86
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev
            - gccgo
            - golang-go
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x86
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev
            - gccgo
            - golang-go
    - compiler: gcc
      dist: precise
      env: PLATFORM=x86
           DIST=precise
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
            - gccgo
            - golang-go
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x86
           DIST=trusty
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
            - gccgo
            - golang-go
    - compiler: clang
      dist: precise
      env: PLATFORM=x86
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev
            - gccgo
            - golang-go
    - compiler: clang
      dist: trusty
      env: PLATFORM=x86
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev
            - gccgo
            - golang-go
    - compiler: clang
      dist: precise
      env: PLATFORM=x86
           DIST=precise
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
            - gccgo
            - golang-go
    - compiler: clang
      dist: trusty
      env: PLATFORM=x86
           DIST=trusty
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev:i386
            - libc6-dev:i386
            - gcc-multilib
            - gccgo:i386
            - golang-go:i386
    - compiler: clang
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
           NOOPT=1
      addons:
        apt:
          packages:
            - libreadline-dev
            - gccgo
            - golang-go
    - compiler: tcc
      dist: precise
      env: PLATFORM=x86_64
           DIST=precise
      addons:
        apt:
          packages:
            - libreadline-dev
            - tcc
            - gccgo
            - golang-go
    - compiler: tcc
      dist: trusty
      env: PLATFORM=x86_64
           DIST=trusty
      addons:
        apt:
          packages:
            - libreadline-dev
            - tcc
            - gccgo
            - golang-go
    - compiler: gcc
      dist: trusty
      env: PLATFORM=x32
      addons:
        apt:
          packages:
            - libc6-dev-x32
            - gcc-multilib
            - gccgo
            - golang-go
    - compiler: powerpc-linux-gnu-gcc
      dist: trusty
      env: PLATFORM=powerpc
      addons:
        apt:
          packages:
            - gcc-powerpc-linux-gnu
            - libc6-dev-powerpc-cross
            - qemu-user
            - gccgo
            - golang-go
    - compiler: arm-linux-gnueabi-gcc
      dist: trusty
      env: PLATFORM=arm
      addons:
        apt:
          packages:
            - gcc-arm-linux-gnueabi
            - libc6-dev-armel-cross
            - qemu-user
            - gccgo
            - golang-go
    - compiler: gcc
      env:
      - secure: "rH+rQS0W+0U3C/W/uRqJ8E5A3KrlbWaDRpZtdT1/SO0kEMnmuG2b0UvoadcIKOEXNHnQeZ3kPQbG2Wjfo/D6up0mXGZLXAvaJZozagxdfF2QPHSpvj2NDRLM71+UaKK/ksq3auPq+o3Y74FZOc4oBr7kPpr01H0pK8/2lljxS2daINRgFfcsaRhKNshtvHBn/KLgbwa5vEB/jadKBKM+mgAYE1sFv8P3yZ3+MzxygpurJ6enU6/9JITF5QgB11ybivYCbqoEf+IhzxgsmELz0zgL+PCVzTvrrNzpCT1UZJ35vWht5Yf7/AmK3sI/rMJm7TYswFKAc7NUbn80oIw6opp7sW1oFqMEHnHNLMNSljg8BwUrbH+y6+yV7sRfG6djCTYUYGYY9ZC2Ef4r3s3ZrRwHuBujZx/DOnFj0nd0AuvETNPkMWD1996bvSQ+WkfZ4JdW335/G61GdQv7kMTutWLKrlDquqxKM1AsoP1d99vCBzpEfRKyZjDUUSmnjdvZ/QgIDidGzH3vYFO81N39HjgKZlxH+oCuoX2ak3A6BrOT7t6mgEXnGM4H9vWhoKb7hseadBsR7YnbFSRmF2FDihEoIJ/BCPykGSZWzxTF94zC3WURI1C3HL0sAHGg3M620FgFj3M4Xkf0CPsmdsjwsnZg6TgVkYwAaKKP0HI2MFs="
      addons:
          apt:
            packages:
              - libreadline-dev
              - gccgo
              - golang-go
          coverity_scan:
            project:
              name: "pali/udftools"
              description: "Build submitted via Travis CI"
            notification_email: pali.rohar@gmail.com
            build_command_prepend: "./autogen.sh && ./configure"
            build_command: make
            branch_pattern: master

before_script:
  - if ! which "$CC" &>/dev/null; then export CC=${CC%%-*}; fi
  - if [ -z "$NOOPT" ]; then export CFLAGS="$CFLAGS -O2"; fi
  - if [[ "$CC" =~ "gcc" && "$CC" != "gcc-4.4" ]]; then export CFLAGS="$CFLAGS -Wno-error=unused-but-set-variable"; fi # needed for AC_PROG_CC_C99
  - if [[ "$CC" =~ "clang" ]]; then export CFLAGS="$CFLAGS -Wno-error=unused-function"; fi # -Werror=unused-function is broken on clang
  - case "$PLATFORM" in
      "x86")       export CFLAGS="-m32 $CFLAGS" ;;
      "x86_64"|"") ;;
      "x32")       export CFLAGS="-mx32 $CFLAGS"; export LDFLAGS="--static" ;;
      "powerpc")   export CONFIGURE_FLAGS="--host=powerpc-linux-gnu"; export LDFLAGS="--static"; export RUN=qemu-ppc ;;
      "arm")       export CONFIGURE_FLAGS="--host=arm-linux-gnueabi"; export LDFLAGS="--static"; export RUN=qemu-arm ;;
      *)           echo "Unsupported platform '$PLATFORM'"; exit 1 ;;
    esac
# CMocka installation
  - cd ..; mkdir cmocka; cd cmocka; PTH=$(pwd); cd ..;
  - wget --no-check-certificate https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar xf cmocka-1.1.0.tar.xz
  - cd cmocka-1.1.0
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PTH -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make install
  - cd ../../udftools
# git-lfs installation
#  - cd ..; mkdir git-lfs; cd git-lfs;
#  - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/git-lfs-install.sh
#  - chmod +x git-lfs-install.sh
#  - ./git-lfs-install.sh
# Configure flags
  - export CFLAGS="-W -Wall -Werror -g $CFLAGS"
  - export PATH="$PTH:$PATH"
  - export LD_LIBRARY_PATH="$PTH/lib:$LD_LIBRARY_PATH"
  - export CFLAGS="$CFLAGS -I$PTH/include/"
  - export LDFLAGS="$LDFLAGS -L$PTH/lib/"
  - export CONFIGURE_FLAGS="$CONFIGURE_FLAGS --enable-tests"

script:
  - set -e
  - if [ -n "$COVERITY_SCAN_TOKEN" ]; then exit 0; fi
  - ./autogen.sh
  - ./configure $CONFIGURE_FLAGS
  - make
  - set +e
  - ./udffsck/travis-tests.sh unit
    # Temporarily disabled.
  - ./udffsck/travis-tests.sh basic
    #  - ./udffsck/travis-tests.sh extra1
    # - ./udffsck/travis-tests.sh extra2

