language: c

compiler:
  - gcc
  - clang

addons: &addons
  apt:
    packages:
      - libreadline-dev

        #matrix:
        # include:
        # - compiler: gcc
        #addons:
        # <<: *addons
        #coverity_scan:
        #  project:
        #    name: "argorain/udftools"
        #    description: "Build submitted via Travis CI"
        #  notification_email: vojtech.vladyka@gmail.com
        #  build_command_prepend: "./autogen.sh && ./configure"
        #  build_command: make
        #  branch_pattern: master
     - 

before_script:
  - export CFLAGS="-W -Wall -O2 -g"
  - cd ..
  - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/decompress-samples.sh
  - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/decompress-samples-extra.sh
  - mkdir cmocka
  - PTH=$(pwd)
  - export PATH=$PTH:$PATH
  - wget --no-check-certificate https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar xf cmocka-1.1.0.tar.xz
  - cd cmocka-1.1.0
  - sudo apt-get -y install cmake
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=PTH -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make install
  - cd ../../udftools

script:
  - if [ -n "$COVERITY_SCAN_TOKEN" ]; then exit 0; fi
  - ./autogen.sh
  - ./configure
  - make
  - wget --no-check-certificate https://pac.chapadla.cz/~rain/udffsck-test-samples/udf-samples.tar.xz 
  - bash decompress-samples.sh
  - cd udftools/udffsck
  - ./test
  - cd ../..
  - rm udf-samples.tar.xz udf-samples -r
  - wget --no-check-certificate https://pac.chapadla.cz/~rain/udffsck-test-samples/udf-samples-extra.tar.xz 
  - bash decompress-samples-extra.sh
  - cd udftools/udffsck
  - ./testextra
