language: c

before_script:
    - ls
    - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
    - tar xf cmocka-1.1.0.tar.xz
    - cd cmocka-1.1.0
    - sudo apt-get -y install cmake
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
    - make
    - sudo make install
    - cd ..
    - cd ..

script:
    - ./autogen.sh
    - ./configure
    - make

after_script:
    - ls
    - cd udffsck
    - ./test
    
