language: c

compiler:
    - clang
before_script:
    - pwd
    - cd ..
    - wget --no-check-certificate https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
    - tar xf cmocka-1.1.0.tar.xz
    - cd cmocka-1.1.0
    - sudo apt-get -y install cmake
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release ..
    - make
    - sudo make install
    - cd ../../udftools

script:
    - ./autogen.sh
    - ./configure
    - make

after_script:
    - cd ..
    - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/udf-samples.tar.xz
    - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/decompress-samples.sh
    - bash decompress-samples.sh
    - ls
    - cd udftools/udffsck
    - ./test
    
