language: c

compiler:
  - gcc
  - clang

addons: &addons
  apt:
    packages:
      - libreadline-dev

matrix:
  include:
    - compiler: gcc
      addons:
        <<: *addons
        #coverity_scan:
        #  project:
        #    name: "argorain/udftools"
        #    description: "Build submitted via Travis CI"
        #  notification_email: vojtech.vladyka@gmail.com
        #  build_command_prepend: "./autogen.sh && ./configure"
        #  build_command: make
        #  branch_pattern: master
    - compiler: clang
      addons:
        <<: *addons
        #coverity_scan:
        #  project:
        #    name: "argorain/udftools"
        #    description: "Build submitted via Travis CI"
        #  notification_email: vojtech.vladyka@gmail.com
        #  build_command_prepend: "./autogen.sh && ./configure"
        #  build_command: make
        #  branch_pattern: master

before_script:
  - export CFLAGS="-W -Wall -O2 -g"

script:
  - if [ -n "$COVERITY_SCAN_TOKEN" ]; then exit 0; fi
  - ./autogen.sh
  - ./configure
  - make
