language: c

compiler:
  - gcc
  - clang

env:
  - DEBUG=
  - DEBUG=--enable-debug

addons: &addons
  apt:
    packages:
      - libreadline-dev
      - cmake

        #matrix:
        # include:
        # - compiler: gcc
        #addons:
        # <<: *addons
        #coverity_scan:
        #  project:
        #    name: "argorain/udftools"
        #    description: "Build submitted via Travis CI"
        #  notification_email: vojtech.vladyka@gmail.com
        #  build_command_prepend: "./autogen.sh && ./configure"
        #  build_command: make
        #  branch_pattern: master

before_script:
  - cd ..
  - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/decompress-samples.sh
  - wget --no-check-certificate https://github.com/argorain/udffsck-test-samples/raw/master/decompress-samples-extra.sh
  - mkdir cmocka
  - cd cmocka
  - PTH=$(pwd)
  - cd ..
  - export PATH="$PTH:$PATH"
  - export LD_LIBRARY_PATH="$PTH/lib"
  - export CFLAGS="-W -Wall -O2 -g -I$PTH/include/"
  - export LDFLAGS="-L$PTH/lib/"
  - wget --no-check-certificate https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar xf cmocka-1.1.0.tar.xz
  - cd cmocka-1.1.0
    #  - sudo apt-get -y install cmake
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=$PTH -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make install
  - cd ../../udftools

script:
  - if [ -n "$COVERITY_SCAN_TOKEN" ]; then exit 0; fi
  - ./autogen.sh $DEBUG
  - ./configure $DEBUG
  - make
  - if [ -n "$DEBUG" ]; then ./udffsck/travis-tests.sh; fi

